change in cicd

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -14,7 +14,7 @@ jobs:
     - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
-        node-version: 16
+        node-version: 20
  
     - name: Install dependencies
       run: npm install --legacy-peer-deps
@@ -26,30 +26,30 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-southeast-1
-    - name: CHECK FOR THE BRANCH NAME CONVENTION 
-      run: |
-        branch_name=${GITHUB_REF#refs/heads/}
-          echo "$branch_name"
-          if [[ "$branch_name" != */* ]]; then
-            echo "Invalid branch name format. Workflow canceled."
-            exit 1
-          fi
+    # - name: CHECK FOR THE BRANCH NAME CONVENTION 
+      # run: |
+      #   branch_name=main
+      #     echo "$branch_name"
+      #     if [[ "$branch_name" != */* ]]; then
+      #       echo "Invalid branch name format. Workflow canceled."
+      #       exit 1
+      #     fi
  
-          IFS='/' read -ra branch_parts <<< "$branch_name"
-          if [ "${#branch_parts[@]}" -ne 2 ]; then
-            echo "Invalid branch name format. Workflow canceled."
-            exit 1
-          fi
+      #     IFS='/' read -ra branch_parts <<< "$branch_name"
+      #     if [ "${#branch_parts[@]}" -ne 2 ]; then
+      #       echo "Invalid branch name format. Workflow canceled."
+      #       exit 1
+      #     fi
  
-          bucket_name="${branch_parts[0]}"
-          file_name="${branch_parts[1]}.json"
-          echo "bucketName=$bucket_name" >> $GITHUB_ENV
-          echo "fileName=$file_name" >> $GITHUB_ENV
-          echo "ENVIRONMENT_NAME=${branch_parts[0]}" >> $GITHUB_ENV
-          echo "WHITELABEL_NAME=${branch_parts[1]}" >> $GITHUB_ENV
-    - name: Print Branch Name
-      run: |
-        echo "Branch Name: $GITHUB_REF"
+      #     bucket_name="${branch_parts[0]}"
+      #     file_name="${branch_parts[1]}.json"
+      #     echo "bucketName=$bucket_name" >> $GITHUB_ENV
+      #     echo "fileName=$file_name" >> $GITHUB_ENV
+      #     echo "ENVIRONMENT_NAME=${branch_parts[0]}" >> $GITHUB_ENV
+      #     echo "WHITELABEL_NAME=${branch_parts[1]}" >> $GITHUB_ENV
+    # - name: Print Branch Name
+    #   run: |
+    #     echo "Branch Name: $GITHUB_REF"
  
     # - name: Fetch .env file from S3
     #   run: |
