cicd testing

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -1,48 +1,64 @@
-name: Frontend Deploy to EC2
-
+name: ec2 testing Deployment
+ 
 on:
   push:
-    branches: [ main ]
-
-jobs:
-  deploy-frontend:
+    branches:
+      - main
+jobs:      
+  DeployOnEc2:
     runs-on: ubuntu-latest
-    
     steps:
-    - uses: actions/checkout@v3
-    
+    - name: Checkout
+      uses: actions/checkout@v1
+ 
     - name: Setup Node.js
-      uses: actions/setup-node@v3
+      uses: actions/setup-node@v2
       with:
-        node-version: '18'
-        
-    - name: Install and Build
-      working-directory: ./
-      run: |
-        npm install
-        npm run build
-        
+        node-version: 16
+ 
+    - name: Install dependencies
+      run: npm install --legacy-peer-deps
+ 
+    # login to aws first 
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ secrets.AWS_REGION }}
-      
-    - name: Copy build to EC2 instance
-      uses: appleboy/scp-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ${{ secrets.EC2_USERNAME }}
-        key: ${{ secrets.EC2_SSH_KEY }}
-        source: "build/"
-        target: "/var/www/html" 
-
-    - name: SSH into EC2 and restart server
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ${{ secrets.EC2_USERNAME }}
-        key: ${{ secrets.EC2_SSH_KEY }}
-        script: |
-          cd /var/www/html
+        aws-region: ap-southeast-1
+    - name: CHECK FOR THE BRANCH NAME CONVENTION 
+      run: |
+        branch_name=${GITHUB_REF#refs/heads/}
+          echo "$branch_name"
+          if [[ "$branch_name" != */* ]]; then
+            echo "Invalid branch name format. Workflow canceled."
+            exit 1
+          fi
+ 
+          IFS='/' read -ra branch_parts <<< "$branch_name"
+          if [ "${#branch_parts[@]}" -ne 2 ]; then
+            echo "Invalid branch name format. Workflow canceled."
+            exit 1
+          fi
+ 
+          bucket_name="${branch_parts[0]}"
+          file_name="${branch_parts[1]}.json"
+          echo "bucketName=$bucket_name" >> $GITHUB_ENV
+          echo "fileName=$file_name" >> $GITHUB_ENV
+          echo "ENVIRONMENT_NAME=${branch_parts[0]}" >> $GITHUB_ENV
+          echo "WHITELABEL_NAME=${branch_parts[1]}" >> $GITHUB_ENV
+    - name: Print Branch Name
+      run: |
+        echo "Branch Name: $GITHUB_REF"
+ 
+    # - name: Fetch .env file from S3
+    #   run: |
+    #     aws s3 cp s3://whitelabel-env/${{ env.ENVIRONMENT_NAME }}/${{ env.WHITELABEL_NAME }}.env .env
+    #   env:
+    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
+    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
+ 
+    - name: Build
+      run: CI="" npm run build
+    - name: Deploy static site to S3 bucket
+      run: aws s3 sync ./build/ s3://mirrasia --delete   
